# Generated by Django 5.1.4 on 2025-01-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='mediafiles'),
        ),
    ]
