# Generated by Django 5.1.4 on 2025-01-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0009_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
