# Generated by Django 5.1.4 on 2025-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0010_payment_card_cvv_payment_card_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
